[update] various fixes

diff --git a/pholder b/pholder
--- a/pholder
+++ b/pholder
@@ -1,15 +1,25 @@
 #!/bin/bash
 
 
+
+
+    # default(s)
+    builtin_bind="localhost:7070"
+    builtin_root="/"
+
     # global(s)
     script_dir=$( dirname $0 )
-    builtin_bind="localhost:7070"
+
+    # trap(s)
+    trap "rm -f $script_dir/app/config/global.root; exit" 1 2
+
+
 
 
     # | function(s)
 
         function display_usage {
-            echo "pholder usage: pholder --server [ --built-in | --vagrant ]"
+            echo "pholder usage: pholder --server [ --built-in | --vagrant ] --version"
         }
 
         function input_builtin_bind {
@@ -24,13 +34,31 @@
             fi
         }
 
+        function input_builtin_root {
+            if [   -z "$1" ]; then
+                printf "Enter server root [$builtin_root]: "
+                read input
+            else
+                input="$1"
+            fi
+            if [ ! -z "$input" ]; then
+                if [ -d "$input" ];then
+                    builtin_root="$input"
+                    echo "$input" > "$script_dir/app/config/global.root"
+                else
+                    echo "Invalid root '$input'"
+                    exit 2
+                fi
+            fi
+        }
+
         function start_builtin {
             php -S "$builtin_bind" -t "$script_dir/app/webroot"
         }
 
         function start_vagrant {
             cd "$script_dir/vagrant"
-            vagrant up pholder
+            vagrant "$@"
         }
 
     # function(s) |
@@ -40,6 +68,9 @@
 
         # ? - argv - count
         if [ $# -eq 0 ]; then
+            input_builtin_bind
+            input_builtin_root
+            echo ""
             start_builtin
         fi
 
@@ -49,17 +80,28 @@
                 case "$2" in
                     '--built-in')
                         input_builtin_bind "$3"
+                        input_builtin_root "$4"
                         start_builtin
                         ;;
                     '--vagrant')
-                        start_vagrant
+                        shift
+                        shift
+                        start_vagrant "$@"
                         ;;
                     *)
                         display_usage
                         exit 2
                         ;;
                 esac
-            ;;
+                ;;
+            '--version')
+                echo "Version: `cat "$script_dir/VERSION"`"
+                exit 0
+                ;;
+            *)
+                display_usage
+                exit 2
+                ;;
         esac
 
     # main |
